#!/usr/bin/env zsh

for folder in $(ls -d */)
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done

git clone https://github.com/jeffreytse/zsh-vi-mode.git $HOME/.zsh-vi-mode
git clone https://github.com/zplug/zplug $ZPLUG_HOME
