#!/usr/bin/env zsh

for folder in $(ls -d */)
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done

mkdir $HOME/.zsh-plugins
git clone https://github.com/jeffreytse/zsh-vi-mode.git $HOME/.zsh-plugins/zsh-vi-mode
git clone https://github.com/Aloxaf/fzf-tab $HOME/.zsh-plugins/fzf-tab
